#!/bin/bash
# QUICK DEPLOYMENT COMMANDS FOR BUILD 27
# This file contains the exact commands to execute Build 27

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                  FIXLO iOS BUILD 27 - QUICK START                    ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "All configuration is COMPLETE. Choose your deployment method:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 1: GitHub Actions Workflow (RECOMMENDED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The workflow has EXPO_TOKEN and builds from /mobile directory."
echo ""
echo "Option A: Via GitHub Web Interface"
echo "  1. Go to: https://github.com/Walter905-creator/fixloapp/actions/workflows/eas-build.yml"
echo "  2. Click: 'Run workflow'"
echo "  3. Select branch: copilot/build-ios-27-correct-directory"
echo "  4. Platform: ios"
echo "  5. Profile: production"
echo "  6. Click: 'Run workflow'"
echo ""
echo "Option B: Via GitHub CLI"
echo "  gh workflow run eas-build.yml \\"
echo "    -f platform=ios \\"
echo "    -f profile=production \\"
echo "    -f branch=copilot/build-ios-27-correct-directory"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 2: Using Deployment Script with EXPO_TOKEN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Get EXPO_TOKEN from: https://expo.dev/accounts/fixlo-app/settings/access-tokens"
echo ""
echo "Then run:"
echo "  export EXPO_TOKEN=\"your-token-here\""
echo "  cd /home/runner/work/fixloapp/fixloapp"
echo "  ./deploy-ios-build-27.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 3: Interactive EAS Login"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  eas login"
echo "  cd /home/runner/work/fixloapp/fixloapp/mobile"
echo "  ./scripts/deploy-ios-build-27.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 4: Manual Step-by-Step"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # Authenticate (choose one):"
echo "  eas login"
echo "  # OR"
echo "  export EXPO_TOKEN=\"your-token-here\""
echo ""
echo "  # Navigate to mobile directory"
echo "  cd /home/runner/work/fixloapp/fixloapp/mobile"
echo ""
echo "  # Verify configuration"
echo "  grep -E 'version|buildNumber' app.config.js"
echo "  # Should show: version: \"1.0.27\" and buildNumber: \"27\""
echo ""
echo "  # Build iOS"
echo "  npx eas-cli@latest build --platform ios --profile production --non-interactive"
echo ""
echo "  # Wait 15-25 minutes for build to complete, then list builds"
echo "  npx eas-cli@latest build:list --platform ios --limit 5 --non-interactive"
echo ""
echo "  # Note the Build ID from the output, then submit"
echo "  npx eas-cli@latest submit --platform ios --id <BUILD_ID> --non-interactive"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PRE-BUILD VERIFICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands to verify everything is ready:"
echo ""
echo "  cd /home/runner/work/fixloapp/fixloapp/mobile"
echo "  pwd  # Should be: /home/runner/work/fixloapp/fixloapp/mobile"
echo "  grep -E 'version|buildNumber' app.config.js | head -4"
echo "  # Expected:"
echo "  #   version: \"1.0.27\","
echo "  #   runtimeVersion: \"1.0.27\","
echo "  #   buildNumber: \"27\","
echo "  #   versionCode: 27,"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXPECTED BUILD OUTPUT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "When build starts, you should see:"
echo "  ✔ Using Expo account: fixlo-app"
echo "  ✔ Project: fixloapp"
echo "  ✔ Bundle identifier: com.fixloapp.mobile"
echo "  ✔ Version: 1.0.27 (27)"
echo ""
echo "Build dashboard: https://expo.dev/accounts/fixlo-app/projects/fixloapp/builds"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AFTER BUILD COMPLETES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Note the Build ID (36-character UUID)"
echo "2. Submit to App Store Connect (done automatically by script, or manually)"
echo "3. Monitor App Store Connect: https://appstoreconnect.apple.com"
echo "4. Wait for processing → Waiting for Review status"
echo "5. TestFlight available once processing completes"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CRITICAL REMINDER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Build 27 uses /mobile directory (CORRECT)"
echo "❌ Build 26 used root directory (WRONG)"
echo ""
echo "Always verify you're building from: /home/runner/work/fixloapp/fixloapp/mobile"
echo ""

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                     ALL CONFIGURATION COMPLETE                       ║"
echo "║                   Choose a method above to deploy                    ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
