const fs = require('fs');
const path = require('path');

/**
 * Production sitemap finalizer.
 *
 * The canonical sitemap is generated by client/scripts/generate-sitemap.mjs during
 * the Vite prebuild, alongside the static SEO pages it describes. Historically
 * this root script regenerated a second, conflicting sitemap after the frontend
 * build and overwrote the canonical sitemap with legacy /us and international
 * routes. That created duplicate/canonical and crawl-noise signals in GSC.
 *
 * This script now only copies the already-generated canonical sitemap artifacts
 * from client/public into the Vercel output root.
 */
function finalizeSitemap() {
  const sourceDir = path.join(__dirname, 'client', 'public');
  const outputDir = __dirname;
  const sitemapFiles = fs.readdirSync(sourceDir)
    .filter((name) => /^sitemap(?:-part-\d+)?\.xml$/.test(name));

  if (!sitemapFiles.includes('sitemap.xml')) {
    throw new Error('client/public/sitemap.xml was not generated before finalization');
  }

  for (const name of sitemapFiles) {
    fs.copyFileSync(path.join(sourceDir, name), path.join(outputDir, name));
    console.log(`[sitemap] finalized ${name}`);
  }

  // Remove stale sitemap parts left by older builds.
  for (const name of fs.readdirSync(outputDir)) {
    if (/^sitemap-part-\d+\.xml$/.test(name) && !sitemapFiles.includes(name)) {
      fs.unlinkSync(path.join(outputDir, name));
      console.log(`[sitemap] removed stale ${name}`);
    }
  }

  console.log(`[sitemap] canonical sitemap finalized from frontend build (${sitemapFiles.length} file(s))`);
}

if (require.main === module) finalizeSitemap();
module.exports = { finalizeSitemap };
