services:
  - type: web
    name: handyman-connect
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
