services:
  - type: web
    name: fixloapp-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://www.fixloapp.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.fixloapp.com,https://fixloapp.com
      - key: STRIPE_MONTHLY_PRICE_ID
        value: price_1Rf0cZPQ4Cetf7g6ekd8hPLb
      - key: ADMIN_EMAIL
        value: admin@fixloapp.com
      - key: ADMIN_PASSWORD
        value: FixloAdmin2024!
      - key: JWT_SECRET
        value: supersecretjwtkey
      # Optional environment variables for enhanced functionality
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
