'use strict';

/**
 * FGAInsight — Owner Intelligence Insight
 *
 * Stores generated recommendations and observations for the owner dashboard.
 * Generated by the AI Insight Service from real platform data.
 */

const mongoose = require('mongoose');

const FGAInsightSchema = new mongoose.Schema(
  {
    // ── Insight metadata ──────────────────────────────────────────────────────
    category: {
      type: String,
      enum: [
        'response_time',
        'lead_conversion',
        'market_demand',
        'campaign_performance',
        'recruiter_performance',
        'trade_trend',
        'geography',
        'retention',
        'revenue',
        'general',
      ],
      default: 'general',
      index: true,
    },

    severity: {
      type: String,
      enum: ['info', 'opportunity', 'warning', 'critical'],
      default: 'info',
      index: true,
    },

    // Human-readable insight text
    title:   { type: String, required: true, trim: true },
    message: { type: String, required: true, trim: true },

    // Supporting metrics used to generate this insight
    metric:     { type: String, trim: true, default: '' },   // e.g. 'response_time_pct_change'
    metricValue:{ type: mongoose.Schema.Types.Mixed, default: null },  // raw value
    metricPrevValue: { type: mongoose.Schema.Types.Mixed, default: null }, // comparison value

    // Optional filters (trade/city/state this insight applies to)
    trade:  { type: String, trim: true, default: '' },
    city:   { type: String, trim: true, default: '' },
    state:  { type: String, trim: true, default: '' },
    source: { type: String, trim: true, default: '' },   // campaign source

    // ── Expiry ────────────────────────────────────────────────────────────────
    expiresAt: { type: Date, default: null },  // null = never expires
    isActive:  { type: Boolean, default: true, index: true },

    // ── Generation metadata ───────────────────────────────────────────────────
    generatedBy:  { type: String, default: 'insight-generator', trim: true },
    generatedAt:  { type: Date, default: Date.now },
    dataWindowDays: { type: Number, default: 7 },  // how many days of data used
  },
  {
    timestamps: true,
    collection: 'fga_insights',
  }
);

FGAInsightSchema.index({ isActive: 1, generatedAt: -1 });
FGAInsightSchema.index({ category: 1, isActive: 1 });
FGAInsightSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0, partialFilterExpression: { expiresAt: { $ne: null } } });

module.exports = mongoose.model('FGAInsight', FGAInsightSchema);
