const mongoose = require('mongoose');

/**
 * RecruiterReferralCode Model
 *
 * One-time use codes generated by recruiters (e.g. "PRO-XD92L").
 * Distinct from the permanent recruiterCode on the RecruiterProfile.
 */
const recruiterReferralCodeSchema = new mongoose.Schema({
  code: {
    type: String,
    required: true,
    unique: true,
    uppercase: true,
    index: true
  },

  recruiterId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'RecruiterProfile',
    required: true,
    index: true
  },

  // 'pro' = use on /pro-signup?ref=  |  'recruiter' = use on /recruiter/signup?ref=
  type: {
    type: String,
    enum: ['pro', 'recruiter'],
    default: 'pro'
  },

  isActive: { type: Boolean, default: true },

  // Set when the code is redeemed
  isUsed: { type: Boolean, default: false },
  usedBy: { type: String, default: null },    // pro email or recruiter email
  usedDate: { type: Date, default: null },

  expiresAt: { type: Date, default: null },

  // How many times this code has been viewed/clicked (tracking)
  clicks: { type: Number, default: 0 }
}, {
  timestamps: true
});

recruiterReferralCodeSchema.index({ recruiterId: 1, isActive: 1 });
recruiterReferralCodeSchema.index({ code: 1, isActive: 1 });

/**
 * Generate a one-time code in "PRO-XXXXX" format
 */
recruiterReferralCodeSchema.statics.generateCode = async function (type = 'pro') {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const prefix = type === 'recruiter' ? 'REC' : 'PRO';
  let code;
  let exists = true;
  while (exists) {
    const suffix = Array.from({ length: 5 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
    code = `${prefix}-${suffix}`;
    exists = !!(await this.findOne({ code }));
  }
  return code;
};

module.exports = mongoose.model('RecruiterReferralCode', recruiterReferralCodeSchema);
