// SEO Page Model
// Stores dynamically generated service pages

const mongoose = require('mongoose');

const seoPageSchema = new mongoose.Schema({
  // Page identification
  slug: {
    type: String,
    required: true,
    unique: true,
    index: true,
  },
  service: {
    type: String,
    required: true,
    index: true,
  },
  city: {
    type: String,
    required: true,
    index: true,
  },
  state: {
    type: String,
    required: true,
    default: 'california',
  },
  
  // Content (generated by LLM)
  content: {
    title: String,
    metaDescription: String,
    h1: String,
    intro: String,
    benefits: [String],
    faqs: [{
      question: String,
      answer: String,
    }],
    whyChooseUs: [String],
    howItWorks: [String],
    localTips: String,
    cta: String,
  },
  
  // Structured data
  schema: {
    type: Object,
    default: {},
  },
  
  // Status
  status: {
    type: String,
    enum: ['draft', 'published', 'frozen'],
    default: 'published',
  },
  
  // Metadata
  metadata: {
    createdBy: {
      type: String,
      default: 'seo-agent',
    },
    sourceQuery: String,
    sourceImpressions: Number,
    sourcePosition: Number,
    lastMetaUpdate: Date,
    metaUpdateCount: {
      type: Number,
      default: 0,
    },
    lastContentExpansion: Date,
    contentExpansionCount: {
      type: Number,
      default: 0,
    },
    frozenAt: Date,
    frozenReason: String,
  },
  
  // Performance tracking (updated from GSC)
  performance: {
    impressions: {
      type: Number,
      default: 0,
    },
    clicks: {
      type: Number,
      default: 0,
    },
    ctr: {
      type: Number,
      default: 0,
    },
    position: {
      type: Number,
      default: 0,
    },
    lastUpdated: Date,
  },
}, {
  timestamps: true,
});

// Indexes for efficient queries
seoPageSchema.index({ service: 1, city: 1 }, { unique: true });
seoPageSchema.index({ status: 1 });
seoPageSchema.index({ 'metadata.createdBy': 1 });
seoPageSchema.index({ createdAt: -1 });

// Virtual for full URL
seoPageSchema.virtual('url').get(function() {
  return `https://www.fixloapp.com${this.slug}`;
});

// Instance method to check if page is frozen
seoPageSchema.methods.isFrozen = function() {
  return this.status === 'frozen';
};

// Instance method to freeze page
seoPageSchema.methods.freeze = function(reason) {
  this.status = 'frozen';
  this.metadata.frozenAt = new Date();
  this.metadata.frozenReason = reason;
  return this.save();
};

// Static method to find pages by service
seoPageSchema.statics.findByService = function(service) {
  return this.find({ service }).sort({ createdAt: -1 });
};

// Static method to find pages by city
seoPageSchema.statics.findByCity = function(city) {
  return this.find({ city }).sort({ createdAt: -1 });
};

// Static method to get top performers
seoPageSchema.statics.getTopPerformers = function(limit = 10) {
  return this.find({ status: 'published' })
    .sort({ 'performance.ctr': -1, 'performance.clicks': -1 })
    .limit(limit);
};

const SEOPage = mongoose.model('SEOPage', seoPageSchema);

module.exports = SEOPage;
