export const PRO_TRADES = {
  handyman: {
    label: 'Handyman',
    plural: 'handyman professionals',
    services: ['general repairs', 'door and trim work', 'drywall patches', 'fixture installation'],
    keywords: ['handyman jobs', 'local handyman leads', 'home repair opportunities']
  },
  plumbing: {
    label: 'Plumbing',
    plural: 'plumbing professionals',
    services: ['leak repairs', 'fixture replacement', 'drain work', 'water heater projects'],
    keywords: ['plumbing jobs', 'local plumbing leads', 'plumber opportunities']
  },
  electrical: {
    label: 'Electrical',
    plural: 'electrical professionals',
    services: ['lighting installation', 'outlet and switch work', 'panel upgrades', 'troubleshooting'],
    keywords: ['electrical jobs', 'local electrician leads', 'electrical contractor opportunities']
  },
  painting: {
    label: 'Painting',
    plural: 'painting professionals',
    services: ['interior painting', 'exterior painting', 'cabinet painting', 'touch-up work'],
    keywords: ['painting jobs', 'local painting leads', 'painter opportunities']
  },
  carpentry: {
    label: 'Carpentry',
    plural: 'carpentry professionals',
    services: ['trim carpentry', 'door installation', 'deck repairs', 'custom woodwork'],
    keywords: ['carpentry jobs', 'local carpenter leads', 'carpenter opportunities']
  },
  roofing: {
    label: 'Roofing',
    plural: 'roofing professionals',
    services: ['roof repairs', 'roof replacement', 'storm damage', 'leak inspections'],
    keywords: ['roofing jobs', 'local roofing leads', 'roofer opportunities']
  },
  hvac: {
    label: 'HVAC',
    plural: 'HVAC professionals',
    services: ['system repair', 'maintenance', 'replacement estimates', 'thermostat installation'],
    keywords: ['HVAC jobs', 'local HVAC leads', 'HVAC contractor opportunities']
  },
  landscaping: {
    label: 'Landscaping',
    plural: 'landscaping professionals',
    services: ['yard cleanup', 'lawn care', 'planting', 'hardscape projects'],
    keywords: ['landscaping jobs', 'local landscaping leads', 'landscaper opportunities']
  },
  flooring: {
    label: 'Flooring',
    plural: 'flooring professionals',
    services: ['floor installation', 'floor repair', 'tile work', 'floor replacement'],
    keywords: ['flooring jobs', 'local flooring leads', 'floor installer opportunities']
  },
  cleaning: {
    label: 'House Cleaning',
    plural: 'house-cleaning professionals',
    services: ['recurring cleaning', 'deep cleaning', 'move-out cleaning', 'post-project cleanup'],
    keywords: ['house cleaning jobs', 'local cleaning leads', 'cleaner opportunities']
  },
  'junk-removal': {
    label: 'Junk Removal',
    plural: 'junk-removal professionals',
    services: ['furniture removal', 'garage cleanouts', 'construction debris', 'property cleanups'],
    keywords: ['junk removal jobs', 'local junk removal leads', 'hauling opportunities']
  },
  remodeling: {
    label: 'Remodeling',
    plural: 'remodeling professionals',
    services: ['kitchen remodeling', 'bathroom remodeling', 'basement projects', 'whole-home renovations'],
    keywords: ['remodeling jobs', 'local remodeling leads', 'general contractor opportunities']
  }
};

export const PRO_CITIES = {
  'birmingham-al': { city: 'Birmingham', state: 'AL', region: 'Central Alabama' },
  'huntsville-al': { city: 'Huntsville', state: 'AL', region: 'North Alabama' },
  'anchorage-ak': { city: 'Anchorage', state: 'AK', region: 'Southcentral Alaska' },
  'phoenix-az': { city: 'Phoenix', state: 'AZ', region: 'Phoenix metro' },
  'tucson-az': { city: 'Tucson', state: 'AZ', region: 'Southern Arizona' },
  'little-rock-ar': { city: 'Little Rock', state: 'AR', region: 'Central Arkansas' },
  'los-angeles-ca': { city: 'Los Angeles', state: 'CA', region: 'Los Angeles County' },
  'san-diego-ca': { city: 'San Diego', state: 'CA', region: 'San Diego County' },
  'san-jose-ca': { city: 'San Jose', state: 'CA', region: 'Silicon Valley' },
  'sacramento-ca': { city: 'Sacramento', state: 'CA', region: 'Sacramento metro' },
  'denver-co': { city: 'Denver', state: 'CO', region: 'Denver metro' },
  'colorado-springs-co': { city: 'Colorado Springs', state: 'CO', region: 'Pikes Peak region' },
  'bridgeport-ct': { city: 'Bridgeport', state: 'CT', region: 'Fairfield County' },
  'hartford-ct': { city: 'Hartford', state: 'CT', region: 'Greater Hartford' },
  'wilmington-de': { city: 'Wilmington', state: 'DE', region: 'New Castle County' },
  'jacksonville-fl': { city: 'Jacksonville', state: 'FL', region: 'Northeast Florida' },
  'miami-fl': { city: 'Miami', state: 'FL', region: 'South Florida' },
  'orlando-fl': { city: 'Orlando', state: 'FL', region: 'Central Florida' },
  'tampa-fl': { city: 'Tampa', state: 'FL', region: 'Tampa Bay' },
  'atlanta-ga': { city: 'Atlanta', state: 'GA', region: 'Atlanta metro' },
  'savannah-ga': { city: 'Savannah', state: 'GA', region: 'Coastal Georgia' },
  'honolulu-hi': { city: 'Honolulu', state: 'HI', region: 'Oahu' },
  'boise-id': { city: 'Boise', state: 'ID', region: 'Treasure Valley' },
  'chicago-il': { city: 'Chicago', state: 'IL', region: 'Chicagoland' },
  'springfield-il': { city: 'Springfield', state: 'IL', region: 'Central Illinois' },
  'indianapolis-in': { city: 'Indianapolis', state: 'IN', region: 'Central Indiana' },
  'fort-wayne-in': { city: 'Fort Wayne', state: 'IN', region: 'Northeast Indiana' },
  'des-moines-ia': { city: 'Des Moines', state: 'IA', region: 'Central Iowa' },
  'cedar-rapids-ia': { city: 'Cedar Rapids', state: 'IA', region: 'Eastern Iowa' },
  'wichita-ks': { city: 'Wichita', state: 'KS', region: 'South Central Kansas' },
  'overland-park-ks': { city: 'Overland Park', state: 'KS', region: 'Kansas City metro' },
  'louisville-ky': { city: 'Louisville', state: 'KY', region: 'Kentuckiana' },
  'lexington-ky': { city: 'Lexington', state: 'KY', region: 'Bluegrass region' },
  'new-orleans-la': { city: 'New Orleans', state: 'LA', region: 'Greater New Orleans' },
  'baton-rouge-la': { city: 'Baton Rouge', state: 'LA', region: 'Capital region' },
  'portland-me': { city: 'Portland', state: 'ME', region: 'Southern Maine' },
  'baltimore-md': { city: 'Baltimore', state: 'MD', region: 'Baltimore metro' },
  'frederick-md': { city: 'Frederick', state: 'MD', region: 'Western Maryland' },
  'boston-ma': { city: 'Boston', state: 'MA', region: 'Greater Boston' },
  'springfield-ma': { city: 'Springfield', state: 'MA', region: 'Pioneer Valley' },
  'detroit-mi': { city: 'Detroit', state: 'MI', region: 'Metro Detroit' },
  'grand-rapids-mi': { city: 'Grand Rapids', state: 'MI', region: 'West Michigan' },
  'minneapolis-mn': { city: 'Minneapolis', state: 'MN', region: 'Twin Cities' },
  'st-paul-mn': { city: 'St. Paul', state: 'MN', region: 'Twin Cities' },
  'jackson-ms': { city: 'Jackson', state: 'MS', region: 'Central Mississippi' },
  'gulfport-ms': { city: 'Gulfport', state: 'MS', region: 'Mississippi Gulf Coast' },
  'kansas-city-mo': { city: 'Kansas City', state: 'MO', region: 'Kansas City metro' },
  'st-louis-mo': { city: 'St. Louis', state: 'MO', region: 'Greater St. Louis' },
  'billings-mt': { city: 'Billings', state: 'MT', region: 'South Central Montana' },
  'missoula-mt': { city: 'Missoula', state: 'MT', region: 'Western Montana' },
  'omaha-ne': { city: 'Omaha', state: 'NE', region: 'Omaha metro' },
  'lincoln-ne': { city: 'Lincoln', state: 'NE', region: 'Southeast Nebraska' },
  'las-vegas-nv': { city: 'Las Vegas', state: 'NV', region: 'Las Vegas Valley' },
  'reno-nv': { city: 'Reno', state: 'NV', region: 'Northern Nevada' },
  'manchester-nh': { city: 'Manchester', state: 'NH', region: 'Southern New Hampshire' },
  'newark-nj': { city: 'Newark', state: 'NJ', region: 'North Jersey' },
  'jersey-city-nj': { city: 'Jersey City', state: 'NJ', region: 'Hudson County' },
  'albuquerque-nm': { city: 'Albuquerque', state: 'NM', region: 'Central New Mexico' },
  'santa-fe-nm': { city: 'Santa Fe', state: 'NM', region: 'Northern New Mexico' },
  'new-york-ny': { city: 'New York', state: 'NY', region: 'New York City' },
  'buffalo-ny': { city: 'Buffalo', state: 'NY', region: 'Western New York' },
  'charlotte-nc': { city: 'Charlotte', state: 'NC', region: 'Charlotte metro' },
  'raleigh-nc': { city: 'Raleigh', state: 'NC', region: 'Triangle area' },
  'greensboro-nc': { city: 'Greensboro', state: 'NC', region: 'Piedmont Triad' },
  'fargo-nd': { city: 'Fargo', state: 'ND', region: 'Red River Valley' },
  'bismarck-nd': { city: 'Bismarck', state: 'ND', region: 'Central North Dakota' },
  'columbus-oh': { city: 'Columbus', state: 'OH', region: 'Central Ohio' },
  'cleveland-oh': { city: 'Cleveland', state: 'OH', region: 'Northeast Ohio' },
  'cincinnati-oh': { city: 'Cincinnati', state: 'OH', region: 'Greater Cincinnati' },
  'oklahoma-city-ok': { city: 'Oklahoma City', state: 'OK', region: 'Central Oklahoma' },
  'tulsa-ok': { city: 'Tulsa', state: 'OK', region: 'Northeast Oklahoma' },
  'portland-or': { city: 'Portland', state: 'OR', region: 'Portland metro' },
  'eugene-or': { city: 'Eugene', state: 'OR', region: 'Willamette Valley' },
  'philadelphia-pa': { city: 'Philadelphia', state: 'PA', region: 'Delaware Valley' },
  'pittsburgh-pa': { city: 'Pittsburgh', state: 'PA', region: 'Western Pennsylvania' },
  'providence-ri': { city: 'Providence', state: 'RI', region: 'Greater Providence' },
  'charleston-sc': { city: 'Charleston', state: 'SC', region: 'Lowcountry' },
  'columbia-sc': { city: 'Columbia', state: 'SC', region: 'Midlands' },
  'sioux-falls-sd': { city: 'Sioux Falls', state: 'SD', region: 'Southeast South Dakota' },
  'rapid-city-sd': { city: 'Rapid City', state: 'SD', region: 'Black Hills' },
  'nashville-tn': { city: 'Nashville', state: 'TN', region: 'Middle Tennessee' },
  'memphis-tn': { city: 'Memphis', state: 'TN', region: 'West Tennessee' },
  'knoxville-tn': { city: 'Knoxville', state: 'TN', region: 'East Tennessee' },
  'houston-tx': { city: 'Houston', state: 'TX', region: 'Greater Houston' },
  'dallas-tx': { city: 'Dallas', state: 'TX', region: 'Dallas-Fort Worth' },
  'san-antonio-tx': { city: 'San Antonio', state: 'TX', region: 'South Central Texas' },
  'austin-tx': { city: 'Austin', state: 'TX', region: 'Central Texas' },
  'salt-lake-city-ut': { city: 'Salt Lake City', state: 'UT', region: 'Wasatch Front' },
  'provo-ut': { city: 'Provo', state: 'UT', region: 'Utah Valley' },
  'burlington-vt': { city: 'Burlington', state: 'VT', region: 'Northwestern Vermont' },
  'virginia-beach-va': { city: 'Virginia Beach', state: 'VA', region: 'Hampton Roads' },
  'richmond-va': { city: 'Richmond', state: 'VA', region: 'Central Virginia' },
  'seattle-wa': { city: 'Seattle', state: 'WA', region: 'Puget Sound' },
  'spokane-wa': { city: 'Spokane', state: 'WA', region: 'Inland Northwest' },
  'charleston-wv': { city: 'Charleston', state: 'WV', region: 'Kanawha Valley' },
  'morgantown-wv': { city: 'Morgantown', state: 'WV', region: 'North Central West Virginia' },
  'milwaukee-wi': { city: 'Milwaukee', state: 'WI', region: 'Southeast Wisconsin' },
  'madison-wi': { city: 'Madison', state: 'WI', region: 'South Central Wisconsin' },
  'cheyenne-wy': { city: 'Cheyenne', state: 'WY', region: 'Southeast Wyoming' }
};

export const PRO_TRADE_SLUGS = Object.keys(PRO_TRADES);
export const PRO_CITY_SLUGS = Object.keys(PRO_CITIES);
