name: EAS Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'ios or android'
        type: choice
        options: [ios, android]
        required: true
      profile:
        description: 'development, preview, or production'
        type: choice
        options: [development, preview, production]
        required: true
      branch:
        description: 'Git branch to build from'
        default: main
        required: true
  # Uncomment to auto-build on pushes to main:
  # push:
  #   branches: [ main ]

jobs:
  eas-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      - name: Validate Expo app presence
        run: |
          if [ ! -f "app.json" ] && ! ls app.config.* >/dev/null 2>&1; then
            echo "❌ No app.json or app.config.* found in mobile/"; exit 1;
          fi
      - run: npm ci
      - run: npx eas-cli@latest --version
      - name: Run EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          npx eas-cli@latest build \
            --platform "${{ github.event.inputs.platform }}" \
            --profile  "${{ github.event.inputs.profile }}" \
            --non-interactive \
            --no-wait
      - name: Show recent builds
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas-cli@latest build:list --limit=5
